[package]
name = "py_ltl_engine"
version = "0.2.0"
edition = "2021"

[lib]
name = "py_ltl_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.1", features = ["extension-module"] }
rand_pcg = "0.3.1"
rand = "0.8.5"